//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbRequest
    {
        public int RequestId { get; set; }
        public int ProviderId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public double Qty { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
    }
}
