//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceProject2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceProject2.Resources.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string btnDiscard {
            get {
                return ResourceManager.GetString("btnDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string btnRequest {
            get {
                return ResourceManager.GetString("btnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        internal static string lblAboutApp {
            get {
                return ResourceManager.GetString("lblAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string lblCost {
            get {
                return ResourceManager.GetString("lblCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage1 {
            get {
                return ResourceManager.GetString("lblLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string lblOrders {
            get {
                return ResourceManager.GetString("lblOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic Image.
        /// </summary>
        internal static string lblPicImage {
            get {
                return ResourceManager.GetString("lblPicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lblQty {
            get {
                return ResourceManager.GetString("lblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string lblRequests {
            get {
                return ResourceManager.GetString("lblRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service.
        /// </summary>
        internal static string lblRequestService {
            get {
                return ResourceManager.GetString("lblRequestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Provider.
        /// </summary>
        internal static string lblSelectProvider {
            get {
                return ResourceManager.GetString("lblSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string lblServices {
            get {
                return ResourceManager.GetString("lblServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string lblShare {
            get {
                return ResourceManager.GetString("lblShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string lblTerms {
            get {
                return ResourceManager.GetString("lblTerms", resourceCulture);
            }
        }
    }
}
